language: php

php:
    #- "7.2"
    - "7.4"
    - hhvm
    - nightly

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm

sudo: false

git:
    submodules: false

before_script:
    - sudo apt-get install sqlite3
    - make install check

script:
    - sqlite3 data/db.sqlite < sql/cat_sqlite.sql
    - chmod 777 data
    - make test

env:
    global:
        - XDEBUG_MODE=coverage

# notifications:
#     irc: "irc.freenode.org#dbwebb"
#     urls:
        # # canax
        # - https://webhooks.gitter.im/e/6e4660b0024de67de0af
        # # canax/commons
        # - https://webhooks.gitter.im/e/dd6775c1f5b11b7421da
#     on_success: change  # options: [always|never|change] default: always
#     on_failure: always  # options: [always|never|change] default: always
#     on_start: never     # options: [always|never|change] default: always
